const BASE='https://api.airtable.com/v0';
const CACHE_TTL=5*60*1000;
let cache={at:0,data:null};

const TABLES={issues:'Questões Eleitorais',theses:'Teses Eleitorais',precedents:'Precedentes Eleitorais',consultations:'Consultas Mesa Eleitoral',cards:'Cartões'};

function clean(v=''){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function selectName(v){return typeof v==='string'?v:(v&&v.name)||''}
function uniq(a){return [...new Set((a||[]).filter(Boolean))]}
function uniqById(a){const m=new Map();for(const x of a||[])if(x?.id&&!m.has(x.id))m.set(x.id,x);return [...m.values()]}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function authorized(request,env){const key=request.headers.get('x-puxe-key')||'';return !!key&&(await sha256(key))===env.APP_ACCESS_HASH}
async function airtable(env,table,params='',init={}){let last='';for(let attempt=0;attempt<5;attempt++){const r=await fetch(`${BASE}/${env.AIRTABLE_BASE_ID}/${encodeURIComponent(table)}${params}`,{...init,headers:{Authorization:`Bearer ${env.AIRTABLE_TOKEN}`,'content-type':'application/json',...(init.headers||{})}});if(r.ok)return r.json();last=await r.text();if(r.status!==429&&r.status<500)throw new Error(`Airtable ${r.status}: ${last}`);await sleep(180*Math.pow(2,attempt)+Math.floor(Math.random()*100))}throw new Error(`Airtable temporariamente indisponível: ${last}`)}
async function getAll(env,table,limit=500){let offset='',records=[];do{const q=new URLSearchParams({pageSize:'100'});if(offset)q.set('offset',offset);const d=await airtable(env,table,`?${q}`);records.push(...(d.records||[]));offset=d.offset||''}while(offset&&records.length<limit);return records}
function tokens(s){return uniq((clean(s).match(/[a-z0-9]{3,}/g)||[]).filter(x=>!['que','para','com','sem','uma','das','dos','por','quando','qual','quais','como','esta','este','eleitoral','eleicoes'].includes(x)))}
function score(query,text){const q=clean(query),hay=clean(text);if(!q)return 1;let s=hay.includes(q)?55:0;const ts=tokens(q);for(const t of ts)if(hay.includes(t))s+=8;if(ts.length){const hit=ts.filter(t=>hay.includes(t)).length;s+=Math.round(25*hit/ts.length)}return s}
function issueText(f){return [f['Questão'],f['Tema eleitoral'],f['Subquestões'],f['Critérios relevantes'],f['Fundamento normativo esperado'],f['Pegadinhas / distinções'],f['Palavras-chave']].join(' ')}
function thesisText(f){return [f['Tese'],f['Tema eleitoral'],f['Formulação consolidada'],f['Fundamento normativo'],f['Exceções / ressalvas'],f['Contraprova / riscos'],f['Palavras-chave']].join(' ')}
function precedentText(f){return [f['Precedente'],f['Tribunal'],f['Processo'],f['Tema eleitoral'],f['Tese extraída'],f['Circunstâncias determinantes'],f['Consequência prática'],f['Distinções / ressalvas'],f['Palavras-chave']].map(selectName).join(' ')}
function publicIssue(r){const f=r.fields||{};return{id:r.id,question:f['Questão']||'',theme:f['Tema eleitoral']||'',subquestions:f['Subquestões']||'',criteria:f['Critérios relevantes']||'',foundation:f['Fundamento normativo esperado']||'',distinctions:f['Pegadinhas / distinções']||'',status:selectName(f['Status'])||'',thesisIds:f['Teses']||[],precedentIds:f['Precedentes']||[],cardIds:f['Cartões relacionados']||[],keywords:f['Palavras-chave']||''}}
function publicThesis(r){const f=r.fields||{};return{id:r.id,title:f['Tese']||'',theme:f['Tema eleitoral']||'',statement:f['Formulação consolidada']||'',foundation:f['Fundamento normativo']||'',exceptions:f['Exceções / ressalvas']||'',counter:f['Contraprova / riscos']||'',state:selectName(f['Estado'])||'',confidence:selectName(f['Confiança'])||'',precedentIds:f['Precedentes']||[],cardIds:f['Cartões relacionados']||[],keywords:f['Palavras-chave']||''}}
function publicPrecedent(r){const f=r.fields||{};return{id:r.id,title:f['Precedente']||'',court:selectName(f['Tribunal'])||'',chamber:f['Órgão julgador']||'',process:f['Processo']||'',relator:f['Relator']||'',date:f['Data do julgamento']||'',theme:f['Tema eleitoral']||'',holding:f['Tese extraída']||'',facts:f['Circunstâncias determinantes']||'',effect:f['Consequência prática']||'',distinctions:f['Distinções / ressalvas']||'',value:selectName(f['Valor do precedente'])||'',state:selectName(f['Situação'])||'',source:f['Fonte oficial']||'',officialId:f['Identificador oficial']||'',cardIds:f['Cartões relacionados']||[],keywords:f['Palavras-chave']||''}}
function publicCard(r){const f=r.fields||{};return{id:r.id,ankiId:f['ID Externo']||'',title:(f['Frente / Texto']||f['Verso / Observações']||'Cartão').replace(/\s+/g,' ').slice(0,180),theme:f['Tema sugerido']||''}}
async function load(env){if(cache.data&&Date.now()-cache.at<CACHE_TTL)return cache.data;const [issuesR,thesesR,precedentsR]=await Promise.all([getAll(env,TABLES.issues,300),getAll(env,TABLES.theses,300),getAll(env,TABLES.precedents,500)]);const data={issuesR,thesesR,precedentsR,issues:issuesR.map(publicIssue),theses:thesesR.map(publicThesis),precedents:precedentsR.map(publicPrecedent),loadedAt:new Date().toISOString()};cache={at:Date.now(),data};return data}
async function cardsByIds(env,ids){const list=uniq(ids);if(!list.length)return[];const chunks=[];for(let i=0;i<list.length;i+=20)chunks.push(list.slice(i,i+20));const out=[];for(const chunk of chunks){const formula=`OR(${chunk.map(id=>`RECORD_ID()="${String(id).replace(/"/g,'\\"')}"`).join(',')})`;const p=new URLSearchParams({pageSize:'100',filterByFormula:formula});const d=await airtable(env,TABLES.cards,`?${p}`);out.push(...(d.records||[]).map(publicCard))}return out}
function rankRecords(query,records,rawRecords,textFn,boostIds=new Set()){return records.map((x,i)=>({x,s:score(query,textFn(rawRecords[i]?.fields||{}))+(boostIds.has(x.id)?45:0)})).filter(v=>!query||v.s>0).sort((a,b)=>b.s-a.s)}
function modeName(mode){return mode==='dossier'?'Dossiê':mode==='case'?'Tenho este caso':mode==='foundation'?'Construir fundamentação':mode==='counter'?'Contraprova':'Consulta rápida'}
async function queryMesa(request,env,url){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);const q=String(url.searchParams.get('q')||'').trim().slice(0,6000),mode=String(url.searchParams.get('mode')||'quick');if(!q)return json({error:'Descreva uma questão ou problema eleitoral.'},400);const k=await load(env);
 const issueRank=rankRecords(q,k.issues,k.issuesR,issueText);let issues=issueRank.slice(0,mode==='case'?6:4).map(v=>v.x);const linkedTheses=new Set(issues.flatMap(x=>x.thesisIds)),linkedPrecedents=new Set(issues.flatMap(x=>x.precedentIds));
 const thesisRank=rankRecords(q,k.theses,k.thesesR,thesisText,linkedTheses);let theses=thesisRank.slice(0,mode==='foundation'?6:5).map(v=>v.x);for(const id of linkedTheses){const t=k.theses.find(x=>x.id===id);if(t&&!theses.some(x=>x.id===id))theses.push(t)}theses=theses.slice(0,7);
 const thesisPrecedents=new Set(theses.flatMap(x=>x.precedentIds));const pBoost=new Set([...linkedPrecedents,...thesisPrecedents]);const precedentRank=rankRecords(q,k.precedents,k.precedentsR,precedentText,pBoost);let precedents=precedentRank.slice(0,mode==='foundation'?9:7).map(v=>v.x);for(const id of pBoost){const p=k.precedents.find(x=>x.id===id);if(p&&!precedents.some(x=>x.id===id))precedents.push(p)}precedents=precedents.slice(0,10);
 if(mode==='dossier'){const theme=issues[0]?.theme||theses[0]?.theme||precedents[0]?.theme||'';if(theme){const ct=clean(theme);issues=uniqById([...issues,...k.issues.filter(x=>clean(x.theme)===ct)]).slice(0,8);theses=uniqById([...theses,...k.theses.filter(x=>clean(x.theme)===ct)]).slice(0,10);precedents=uniqById([...precedents,...k.precedents.filter(x=>clean(x.theme)===ct)]).slice(0,14)}}
 const cardIds=uniq([...issues.flatMap(x=>x.cardIds),...theses.flatMap(x=>x.cardIds),...precedents.flatMap(x=>x.cardIds)]);const cards=await cardsByIds(env,cardIds);
 const timeline=precedents.filter(x=>x.date).slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(x=>({id:x.id,date:x.date,title:x.title,process:x.process,court:x.court,state:x.state}));
 const foundation=uniq([...theses.map(x=>x.foundation),...issues.map(x=>x.foundation)]).filter(Boolean);const counterpoints=uniq([...theses.map(x=>x.counter),...theses.map(x=>x.exceptions),...precedents.map(x=>x.distinctions)]).filter(Boolean);const summary=theses[0]?.statement||precedents[0]?.holding||'Ainda não há tese consolidada suficiente no acervo para esta consulta.';
 return json({query:q,mode,modeLabel:modeName(mode),summary,issues,theses,precedents,cards,timeline,foundation,counterpoints,loadedAt:k.loadedAt,warning:'A Mesa recupera apenas conhecimento estruturado e fontes salvas. Confira a fonte oficial antes de citar e use apenas descrição pública ou anonimizada de casos.'})}
async function saveConsultation(request,env){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);const b=await request.json();const q=String(b.query||'').trim().slice(0,6000);if(!q)return json({error:'Consulta vazia.'},400);const now=new Date().toISOString();const mode=modeName(String(b.mode||'quick'));const fields={'Consulta':`Mesa · ${now.slice(0,16).replace('T',' ')} · ${q.replace(/\s+/g,' ').slice(0,90)}`,'Modo':mode,'Pergunta / descrição':q,'Questões identificadas':String((b.issueTitles||[]).join(' | ')).slice(0,8000),'Síntese recuperada':String(b.summary||'').slice(0,12000),'Criada em':now,'Status':'Concluída','Observações':'Consulta salva pela Mesa Eleitoral. Política: usar apenas conteúdo público ou anonimizado; não armazenar minuta interna ou dado processual restrito.'};if(Array.isArray(b.issueIds)&&b.issueIds.length)fields['Questões relacionadas']=uniq(b.issueIds).slice(0,20);if(Array.isArray(b.thesisIds)&&b.thesisIds.length)fields['Teses encontradas']=uniq(b.thesisIds).slice(0,20);if(Array.isArray(b.precedentIds)&&b.precedentIds.length)fields['Precedentes encontrados']=uniq(b.precedentIds).slice(0,30);if(Array.isArray(b.cardIds)&&b.cardIds.length)fields['Cartões relacionados']=uniq(b.cardIds).slice(0,30);const d=await airtable(env,TABLES.consultations,'',{method:'POST',body:JSON.stringify({records:[{fields}]})});return json({ok:true,id:d.records?.[0]?.id||null},201)}

export async function handleMesa(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/mesa/'))return null;try{if(url.pathname==='/api/mesa/query'&&request.method==='GET')return await queryMesa(request,env,url);if(url.pathname==='/api/mesa/consultations'&&request.method==='POST')return await saveConsultation(request,env);if(url.pathname==='/api/mesa/health'&&request.method==='GET')return json({ok:true,version:'1.0',tables:Object.values(TABLES).slice(0,4),cacheTtlSeconds:CACHE_TTL/1000});return json({error:'Rota da Mesa Eleitoral não encontrada.'},404)}catch(e){console.error('Mesa Eleitoral',e);return json({error:e.message||'Falha na Mesa Eleitoral'},500)}}
