const BASE='https://api.airtable.com/v0';
const CACHE_TTL=5*60*1000;
let memory={at:0,data:null};

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function clean(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function uniq(a){return [...new Set((a||[]).filter(Boolean))]}
function selectName(v){return typeof v==='string'?v:(v&&v.name)||''}
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function authorized(request,env){const key=request.headers.get('x-puxe-key')||'';return !!key && (await sha256(key))===env.APP_ACCESS_HASH}
async function airtable(env,table,params='',init={}){if(!env.AIRTABLE_TOKEN)throw new Error('AIRTABLE_TOKEN secret is not configured');const r=await fetch(`${BASE}/${env.AIRTABLE_BASE_ID}/${encodeURIComponent(table)}${params}`,{...init,headers:{Authorization:`Bearer ${env.AIRTABLE_TOKEN}`,'content-type':'application/json',...(init.headers||{})}});if(!r.ok)throw new Error(`Airtable ${r.status}: ${await r.text()}`);return r.json()}
async function getAll(env,table,limit=1200){let offset='',records=[];do{const q=new URLSearchParams({pageSize:'100'});if(offset)q.set('offset',offset);const d=await airtable(env,table,`?${q}`);records.push(...(d.records||[]));offset=d.offset||''}while(offset&&records.length<limit);return records}
function invalidate(){memory={at:0,data:null}}
function mapBy(records,field){return new Map(records.map(r=>[r.id,String(r.fields?.[field]||'')]))}
function linkedNames(ids,map){return uniq((ids||[]).map(id=>map.get(String(id))).filter(Boolean))}
function normalizeCard(r){const f=r.fields||{};return{id:r.id,ankiId:f['ID Externo']||'',front:f['Frente / Texto']||'',body:f['Verso / Observações']||'',historicalContext:f['Contexto Histórico da Doutrina']||'',historicalStatus:f['Contexto Histórico da Doutrina']?'Enriquecido':'Original importado',contextInAnki:!!f['Contexto incorporado ao Anki'],historicalUpdatedAt:f['Atualizado no Contexto Histórico em']||null,conceptIds:(Array.isArray(f['Conceitos vinculados'])&&f['Conceitos vinculados'].length)?f['Conceitos vinculados']:(f['Conceitos detectados (IA)']||[]),themeIds:(Array.isArray(f['Temas vinculados'])&&f['Temas vinculados'].length)?f['Temas vinculados']:(f['Temas detectados (IA)']||[]),raw:f}}
function cardText(c){return clean(`${c.front} ${c.body} ${c.historicalContext}`)}
function historicalText(c){return clean(c.historicalContext||'')}
function tokenSet(s){return new Set((clean(s).match(/[a-z0-9]{5,}/g)||[]).filter(x=>!['sobre','entre','ainda','assim','quando','todos','todas','direito','direitos','estado','forma','mesmo','mesma'].includes(x)))}
function jaccard(a,b){const A=tokenSet(a),B=tokenSet(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(1,new Set([...A,...B]).size)}

async function knowledge(env){
  if(memory.data&&Date.now()-memory.at<CACHE_TTL)return memory.data;
  const [cardsR,conceptsR,themesR,relsR,timelineR,authorsR,theoriesR,historyR]=await Promise.all([
    getAll(env,'Cartões',700),getAll(env,'Conceitos',500),getAll(env,'Temas',250),getAll(env,'Relações Doutrinárias',700),getAll(env,'Linha Histórica',250),getAll(env,'Autores',300),getAll(env,'Teorias',400),getAll(env,'Histórico',1200)
  ]);
  const conceptNames=mapBy(conceptsR,'Conceito'),themeNames=mapBy(themesR,'Tema'),authorNames=mapBy(authorsR,'Autor'),theoryNames=mapBy(theoriesR,'Teoria');
  const conceptMeta=new Map(conceptsR.map(r=>[r.id,{authors:r.fields?.['Autores']||[],theories:r.fields?.['Teorias']||[],themes:r.fields?.['Tema vinculado']||[]}]))
  const cards=cardsR.map(normalizeCard).map(c=>{
    const concepts=linkedNames(c.conceptIds,conceptNames),themes=linkedNames(c.themeIds,themeNames);
    const meta=(c.conceptIds||[]).map(id=>conceptMeta.get(id)||{});
    return {...c,concepts,themes,authors:uniq(meta.flatMap(x=>linkedNames(x.authors,authorNames))),theories:uniq(meta.flatMap(x=>linkedNames(x.theories,theoryNames)))};
  });
  const rels=relsR.filter(r=>selectName(r.fields?.['Status'])!=='Rejeitada').map(r=>({o:clean(r.fields?.['Origem']),v:clean(selectName(r.fields?.['Verbo'])),d:clean(r.fields?.['Destino']),why:r.fields?.['Justificativa']||''}));
  const timeline=timelineR.filter(r=>selectName(r.fields?.['Status'])!=='Inativo').map(r=>({m:clean(r.fields?.['Marco']),t:clean(r.fields?.['Tema']),why:r.fields?.['Relação com anterior']||r.fields?.['Descrição']||'',order:Number(r.fields?.['Ordem']||0)})).sort((a,b)=>a.order-b.order);
  const feedback=new Map();
  for(const r of historyR){const f=r.fields||{};if(!String(f['Evento']||'').startsWith('Feedback Puxe o Fio'))continue;const target=String(f['Alvo externo']||'');const val=clean(f['Depois']||'');if(target)feedback.set(target,val.includes('negativ')?-1:1)}
  const data={cards,conceptNames,themeNames,rels,timeline,feedback,loadedAt:new Date().toISOString()};memory={at:Date.now(),data};return data;
}

function relationEvidence(a,b,k){const A=uniq([...a.concepts,...a.themes,...a.authors,...a.theories]).map(clean),B=uniq([...b.concepts,...b.themes,...b.authors,...b.theories]).map(clean);let best=null;for(const r of k.rels){const direct=A.some(x=>x&&r.o&&(r.o.includes(x)||x.includes(r.o)))&&B.some(x=>x&&r.d&&(r.d.includes(x)||x.includes(r.d)));const reverse=A.some(x=>x&&r.d&&(r.d.includes(x)||x.includes(r.d)))&&B.some(x=>x&&r.o&&(r.o.includes(x)||x.includes(r.o)));if(!direct&&!reverse)continue;let kind='Aprofundamento';if(/crit|contr|diverg|opoe|exce|supera/.test(r.v))kind='Contraste';else if(/evol|desenvol|ampl|sucede|transform/.test(r.v))kind=direct?'Evolução':'Origem';else if(/orig|fundament|anteced|pressup|influ/.test(r.v))kind=direct?'Aprofundamento':'Origem';const e={score:42,kind,why:r.why||`Relação doutrinária: ${r.v||'conexão confirmada'}`,basis:'grafo doutrinário'};if(!best||e.score>best.score)best=e}return best||{score:0,kind:'',why:'',basis:''}}
function historicalEvidence(a,b,k){const A=historicalText(a)||cardText(a),B=historicalText(b)||cardText(b);const matches=x=>(x.m&&A.includes(x.m))||(x.t&&A.includes(x.t));const matchb=x=>(x.m&&B.includes(x.m))||(x.t&&B.includes(x.t));const ma=k.timeline.find(matches),mb=k.timeline.find(matchb);if(!ma||!mb)return{score:0,kind:'',why:'',basis:''};const d=mb.order-ma.order;return{score:d?28:10,kind:d>0?'Evolução':d<0?'Origem':'Aprofundamento',why:mb.why||ma.why||'A linha histórica do acervo aproxima estes dois nós.',basis:'linha histórica'}}
function metadataEvidence(a,b){const shared={concepts:a.concepts.filter(x=>b.concepts.includes(x)),themes:a.themes.filter(x=>b.themes.includes(x)),authors:a.authors.filter(x=>b.authors.includes(x)),theories:a.theories.filter(x=>b.theories.includes(x))};let score=shared.concepts.length*18+shared.themes.length*10+shared.authors.length*12+shared.theories.length*16;const evidence=[];if(shared.concepts.length)evidence.push(`Conceito compartilhado: ${shared.concepts.slice(0,2).join(', ')}`);if(shared.theories.length)evidence.push(`Teoria relacionada: ${shared.theories.slice(0,2).join(', ')}`);if(shared.authors.length)evidence.push(`Autor relacionado: ${shared.authors.slice(0,2).join(', ')}`);if(shared.themes.length)evidence.push(`Tema comum: ${shared.themes.slice(0,2).join(', ')}`);return{score,evidence}}
function semanticEvidence(a,b){const full=jaccard(cardText(a),cardText(b)),hist=jaccard(historicalText(a),historicalText(b));return{score:Math.round(full*25+hist*38),full,hist}}
function feedbackEvidence(a,b,k){const v=k.feedback.get(`${a.ankiId}→${b.ankiId}`);return v===1?{score:35,text:'Conexão já validada por você'}:v===-1?{score:-120,text:'Conexão rejeitada anteriormente'}:{score:0,text:''}}
function classifyKind(a,b,e){if(e.rel.kind)return e.rel.kind;if(e.hist.kind)return e.hist.kind;const bt=clean(`${b.front} ${b.historicalContext}`);if(/critica|contrap|diverg|alternativ|opos/.test(bt))return'Contraste';if(/origem|anteced|seculo|formacao|surge|nascimento/.test(bt))return'Origem';if(/posterior|evolu|desenvolv|amplia|transform/.test(bt))return'Evolução';return'Aprofundamento'}
function label(k){return k==='Origem'?'Quero entender de onde isso veio':k==='Evolução'?'Quero avançar historicamente':k==='Contraste'?'Quero ver outra forma de pensar o problema':'Quero aprofundar a teoria'}
function confidence(score,bases){return score>=70&&bases>=2?'Alta':score>=42?'Média':'Exploratória'}
function scorePair(a,b,visited,k){if(!b||a.id===b.id||visited.has(b.id))return{score:-999};const rel=relationEvidence(a,b,k),hist=historicalEvidence(a,b,k),meta=metadataEvidence(a,b),sem=semanticEvidence(a,b),fb=feedbackEvidence(a,b,k);const score=rel.score+hist.score+meta.score+sem.score+fb.score;const evidence=uniq([fb.text,...meta.evidence,rel.why,hist.why].filter(Boolean));const basis=uniq([fb.text&&'feedback validado',rel.basis,hist.basis,meta.score&&'metadados estruturais',sem.score>=8&&'afinidade semântica'].filter(Boolean));return{score,rel,hist,meta,sem,fb,evidence,basis}}
function bridgeFor(kind,e){if(e.rel.why)return e.rel.why;if(e.hist.why)return e.hist.why;if(e.meta.evidence.length)return `${e.meta.evidence.slice(0,2).join('. ')}. Este vínculo mantém continuidade intelectual suficiente para avançar sem reduzir a relação a mera coincidência lexical.`;return kind==='Origem'?'Este caminho recua para um antecedente conceitual ou histórico que ajuda a explicar a formulação atual.':kind==='Contraste'?'Este caminho mantém o problema central, mas muda a lente teórica para permitir comparação e contraste.':kind==='Evolução'?'Este caminho avança para uma formulação posterior relacionada ao núcleo estudado.':'Este caminho aprofunda um conceito, autor ou teoria estruturalmente associado ao cartão atual.'}
function publicCard(c){return{id:c.id,ankiId:c.ankiId,front:c.front,body:c.body,historicalContext:c.historicalContext,historicalStatus:c.historicalStatus,historicalUpdatedAt:c.historicalUpdatedAt,concepts:c.concepts,themes:c.themes,authors:c.authors,theories:c.theories}}
function searchCards(cards,q){const query=clean(q||'');if(!query)return cards.slice().sort((a,b)=>a.ankiId.localeCompare(b.ankiId)).slice(0,24);const terms=query.split(' ').filter(Boolean);return cards.map(c=>{const hay=clean(`${c.ankiId} ${c.front} ${c.body} ${c.historicalContext} ${c.concepts.join(' ')} ${c.themes.join(' ')} ${c.authors.join(' ')} ${c.theories.join(' ')}`);let s=clean(c.ankiId)===query?120:0;if(hay.includes(query))s+=40;for(const t of terms)if(hay.includes(t))s+=8;return{c,s}}).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,24).map(x=>x.c)}

function mapFromPath(cards,path){const ids=String(path||'').split('→').map(x=>x.trim()).filter(Boolean);const nodes={};let prev=null,root=null;for(const anki of ids){const c=cards.find(x=>x.ankiId===anki);if(!c)continue;if(!root)root=c.id;if(!nodes[c.id])nodes[c.id]={cardId:c.id,ankiId:c.ankiId,title:(c.front||c.body||c.ankiId).slice(0,120),children:[]};if(prev&&nodes[prev]&&!nodes[prev].children.some(x=>x.to===c.id))nodes[prev].children.push({to:c.id,kind:'Aprofundamento',bridge:''});prev=c.id}return{root,nodes}}
function parseMap(f,cards){try{const m=JSON.parse(f['Mapa do fio']||'');if(m&&m.nodes)return m}catch{}return mapFromPath(cards,f['Percurso']||'')}
async function createFio(env,c){const map={root:c.id,nodes:{[c.id]:{cardId:c.id,ankiId:c.ankiId,title:(c.front||c.body||c.ankiId).slice(0,120),children:[]}}};const now=new Date().toISOString();const p={records:[{fields:{'Fio':`Fio — ${c.ankiId}`,'Cartão inicial':[c.id],'Cartão atual':[c.id],'Percurso':c.ankiId,'Mapa do fio':JSON.stringify(map),'Passos':0,'Status':'Em andamento','Último acesso':now,'Observações':'Percurso iniciado pela interface Puxe o Fio v2.'}}]};const d=await airtable(env,'Fios de Estudo','',{method:'POST',body:JSON.stringify(p)});return d.records?.[0]?.id||null}
async function updateFio(env,id,b){const fields={'Último acesso':new Date().toISOString()};if(b.currentCardId)fields['Cartão atual']=[b.currentCardId];if(b.path!=null)fields['Percurso']=b.path;if(b.map!=null)fields['Mapa do fio']=typeof b.map==='string'?b.map:JSON.stringify(b.map);if(b.kind)fields['Último caminho escolhido']=b.kind;if(b.bridge!=null)fields['Última transição contextual']=b.bridge;if(b.steps!=null)fields['Passos']=Number(b.steps);if(b.status)fields['Status']=b.status;if(b.name)fields['Fio']=String(b.name).slice(0,180);if(b.summary!=null)fields['Resumo da descoberta']=b.summary;await airtable(env,'Fios de Estudo','',{method:'PATCH',body:JSON.stringify({records:[{id,fields}]})})}
async function listFios(env,k){const rows=await getAll(env,'Fios de Estudo',500);const cmap=new Map(k.cards.map(c=>[c.id,c]));return rows.map(r=>{const f=r.fields||{},current=(f['Cartão atual']||[])[0],c=cmap.get(current),map=parseMap(f,k.cards);return{id:r.id,name:f['Fio']||'Fio',status:selectName(f['Status'])||'Em andamento',path:f['Percurso']||'',steps:Number(f['Passos']||0),lastAccess:f['Último acesso']||r.createdTime,current:c?publicCard(c):null,map,summary:f['Resumo da descoberta']||'',createdTime:r.createdTime}}).sort((a,b)=>String(b.lastAccess||'').localeCompare(String(a.lastAccess||'')))}
async function feedback(env,b){const value=b.value==='negative'?'negativo':'positivo';const pair=`${b.fromAnki||''}→${b.toAnki||''}`;await airtable(env,'Histórico','',{method:'POST',body:JSON.stringify({records:[{fields:{'Evento':`Feedback Puxe o Fio — ${value}`,'Alvo externo':pair,'Depois':value,'Observações':`Tipo: ${b.kind||''}. Base exibida: ${(b.basis||[]).join(', ')}. ${b.note||''}`}}]})});invalidate()}

async function api(request,env,url){
  if(url.pathname==='/api/health')return json({ok:true,version:'2.0',cacheTtlSeconds:CACHE_TTL/1000});
  if(url.pathname==='/api/session'&&request.method==='POST'){const ok=await authorized(request,env);return json({ok},ok?200:401)}
  if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);
  const k=await knowledge(env);
  if(url.pathname==='/api/dashboard'&&request.method==='GET'){const fios=await listFios(env,k);const enriched=k.cards.filter(c=>c.historicalContext).length,transitions=fios.reduce((n,x)=>n+x.steps,0);return json({stats:{fios:fios.length,enriched,transitions,validated:[...k.feedback.values()].filter(v=>v===1).length},recent:fios.slice(0,5),cacheLoadedAt:k.loadedAt})}
  if(url.pathname==='/api/cards/search'&&request.method==='GET')return json({results:searchCards(k.cards,url.searchParams.get('q')).map(publicCard)});
  if(url.pathname==='/api/random'&&request.method==='GET'){const candidates=k.cards.map(c=>({c,w:(c.historicalContext?30:0)+c.concepts.length*6+c.themes.length*3+c.authors.length*4+c.theories.length*5})).sort((a,b)=>b.w-a.w).slice(0,80);const pick=candidates[Math.floor(Math.random()*Math.max(1,candidates.length))]?.c||k.cards[0];return json({card:publicCard(pick)})}
  if(url.pathname==='/api/thread'&&request.method==='GET'){const id=url.searchParams.get('id'),visited=new Set((url.searchParams.get('visited')||'').split(',').filter(Boolean)),current=k.cards.find(c=>c.id===id||c.ankiId===id)||k.cards[0];if(!current)return json({error:'No cards available'},404);visited.add(current.id);const ranked=k.cards.map(card=>({card,e:scorePair(current,card,visited,k)})).filter(x=>x.e.score>12).sort((a,b)=>b.e.score-a.e.score).slice(0,36);const opts=[],seen=new Set();for(const x of ranked){const kind=classifyKind(current,x.card,x.e);if(seen.has(kind))continue;seen.add(kind);const bases=x.e.basis.length;opts.push({kind,label:label(kind),card:publicCard(x.card),score:x.e.score,confidence:confidence(x.e.score,bases),bridge:bridgeFor(kind,x.e),basis:x.e.basis,evidence:x.e.evidence.slice(0,5)});if(opts.length>=4)break}return json({current:publicCard(current),options:opts,engine:'v2'})}
  if(url.pathname==='/api/fios'&&request.method==='GET')return json({fios:await listFios(env,k)});
  if(url.pathname==='/api/fio/start'&&request.method==='POST'){const b=await request.json(),c=k.cards.find(x=>x.id===b.cardId||x.ankiId===b.cardId);if(!c)return json({error:'Card not found'},404);return json({fioId:await createFio(env,c)})}
  const fioMatch=url.pathname.match(/^\/api\/fio\/(rec[A-Za-z0-9]{14})$/);if(fioMatch&&request.method==='GET'){const fios=await listFios(env,k),fio=fios.find(x=>x.id===fioMatch[1]);return fio?json({fio}):json({error:'Fio not found'},404)}
  if(fioMatch&&request.method==='PATCH'){const b=await request.json();await updateFio(env,fioMatch[1],b);return json({ok:true})}
  const complete=url.pathname.match(/^\/api\/fio\/(rec[A-Za-z0-9]{14})\/complete$/);if(complete&&request.method==='POST'){const b=await request.json();await updateFio(env,complete[1],{status:'Concluído',summary:b.summary||`Percurso consolidado: ${b.path||''}`,path:b.path,map:b.map,steps:b.steps,currentCardId:b.currentCardId});return json({ok:true})}
  if(url.pathname==='/api/feedback'&&request.method==='POST'){await feedback(env,await request.json());return json({ok:true})}
  if(url.pathname==='/api/card/context')return json({error:'Context updates are disabled on the public Worker. Use the shared Airtable integration.'},405);
  return json({error:'API route not found'},404)
}
export default{async fetch(request,env){const url=new URL(request.url);try{if(url.pathname.startsWith('/api/'))return await api(request,env,url);return env.ASSETS.fetch(request)}catch(e){return json({error:e.message},500)}}};
