import app from './worker.js';

const BASE='https://api.airtable.com/v0';
let lastReconcile=0;
const RECONCILE_TTL=10*60*1000;

function clean(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function authorized(request,env){const key=request.headers.get('x-puxe-key')||'';return !!key&&(await sha256(key))===env.APP_ACCESS_HASH}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function airtable(env,table,params='',init={}){const r=await fetch(`${BASE}/${env.AIRTABLE_BASE_ID}/${encodeURIComponent(table)}${params}`,{...init,headers:{Authorization:`Bearer ${env.AIRTABLE_TOKEN}`,'content-type':'application/json',...(init.headers||{})}});if(!r.ok)throw new Error(`Airtable ${r.status}: ${await r.text()}`);return r.json()}
async function getAll(env,table,limit=1500){let offset='',records=[];do{const q=new URLSearchParams({pageSize:'100'});if(offset)q.set('offset',offset);const d=await airtable(env,table,`?${q}`);records.push(...(d.records||[]));offset=d.offset||''}while(offset&&records.length<limit);return records}
function words(s){return new Set((clean(s).match(/[a-z0-9]{4,}/g)||[]))}
function similarity(a,b){const A=words(a),B=words(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(A.size,B.size)}
function indexFields(card){const f=card.fields||{},id=f['ID Externo']||card.id,front=String(f['Frente / Texto']||''),back=String(f['Verso / Observações']||''),ctx=String(f['Contexto Histórico da Doutrina']||''),theme=String(f['Tema sugerido']||''),concepts=String(f['Conceitos sugeridos']||'');return{'Entrada':`${id} — ${(front||back||'Cartão').replace(/\s+/g,' ').slice(0,110)}`,'Tipo':'Cartão','Resumo pesquisável':`${front}\n${back}\n${ctx}`.slice(0,8000),'Palavras-chave':`${theme}; ${concepts}`.slice(0,3000),'Tabela fonte':'Cartões','Registro fonte':card.id,'Provenance':`${f['Origem da ingestão']?.name||f['Origem da ingestão']||'Airtable'}${f['Fingerprint do conteúdo']?` · fingerprint ${f['Fingerprint do conteúdo']}`:''}`,'Status':'Ativo'}}
async function ensureIndexForCard(env,card,indexRows){let idx=indexRows.find(r=>String(r.fields?.['Registro fonte']||'')===card.id);const fields=indexFields(card);if(idx){await airtable(env,'Índice Universal','',{method:'PATCH',body:JSON.stringify({records:[{id:idx.id,fields}]})});return'updated'}await airtable(env,'Índice Universal','',{method:'POST',body:JSON.stringify({records:[{fields}]})});return'created'}
async function reconcileIndex(env,force=false){if(!force&&Date.now()-lastReconcile<RECONCILE_TTL)return{skipped:true};const [cards,index]=await Promise.all([getAll(env,'Cartões',1200),getAll(env,'Índice Universal',1800)]);const indexed=new Set(index.map(r=>String(r.fields?.['Registro fonte']||'')));let created=0;for(const card of cards){if(indexed.has(card.id))continue;await ensureIndexForCard(env,card,index);indexed.add(card.id);created++}lastReconcile=Date.now();return{cards:cards.length,index:index.length+created,created}}
async function ingest(request,env){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);const b=await request.json();const front=String(b.front||'').trim(),back=String(b.back||'').trim(),deck=String(b.deck||'Novo baralho').trim();if(!front&&!back)return json({error:'Informe frente ou verso do cartão.'},400);const fp=(await sha256(`${clean(deck)}|${clean(front)}|${clean(back)}`)).slice(0,16);const cards=await getAll(env,'Cartões',1200);const exact=cards.find(r=>String(r.fields?.['Fingerprint do conteúdo']||'')===fp||(b.externalId&&String(r.fields?.['ID Externo']||'')===String(b.externalId)));if(exact){return json({ok:true,status:'existing',cardId:exact.id,externalId:exact.fields?.['ID Externo'],fingerprint:fp})}
const near=cards.map(r=>({r,s:similarity(front,String(r.fields?.['Frente / Texto']||''))})).filter(x=>x.s>=0.92).sort((a,b)=>b.s-a.s).slice(0,3);if(near.length)return json({error:'Possível cartão já existente. Criação bloqueada para revisão conservadora.',fingerprint:fp,candidates:near.map(x=>({id:x.r.id,externalId:x.r.fields?.['ID Externo'],similarity:Number(x.s.toFixed(3)),front:String(x.r.fields?.['Frente / Texto']||'').slice(0,220)}))},409);
const externalId=String(b.externalId||`CARD-${fp.slice(0,12).toUpperCase()}`),now=new Date().toISOString();const fields={'ID Externo':externalId,'Frente / Texto':front,'Verso / Observações':back,'Baralho Anki':deck,'Origem da ingestão':'Chat — estudo','Inserido na base em':now,'Fingerprint do conteúdo':fp};if(b.origin)fields['Origem / Banca']=String(b.origin);if(b.tags)fields['Tags originais']=String(b.tags);if(b.theme)fields['Tema sugerido']=String(b.theme);if(b.concepts)fields['Conceitos sugeridos']=Array.isArray(b.concepts)?b.concepts.join('; '):String(b.concepts);if(b.historicalContext){fields['Contexto Histórico da Doutrina']=String(b.historicalContext);fields['Status de enriquecimento histórico']='Enriquecido';fields['Origem do enriquecimento histórico']='Contexto Histórico da Doutrina';fields['Versão do contexto histórico']=1;fields['Atualizado no Contexto Histórico em']=now}
const created=await airtable(env,'Cartões','',{method:'POST',body:JSON.stringify({records:[{fields}]})});const card=created.records?.[0];if(!card)throw new Error('Cartão não foi criado.');const indexRows=await getAll(env,'Índice Universal',1800);await ensureIndexForCard(env,card,indexRows);await airtable(env,'Histórico','',{method:'POST',body:JSON.stringify({records:[{fields:{'Evento':'Ingestão de cartão por chat','Alvo externo':externalId,'Depois':`Criado ${externalId} · fingerprint ${fp}`,'Observações':'Ingestão + deduplicação determinística + indexação incremental. Conteúdo original preservado.'}}]})});lastReconcile=0;return json({ok:true,status:'created',cardId:card.id,externalId,fingerprint:fp,indexed:true},201)}

export default{async fetch(request,env){const url=new URL(request.url);try{
if(url.pathname==='/api/health'&&request.method==='GET')return json({ok:true,version:'2.2',features:{readerTools:true,keyboardShortcuts:['1','2','3','4','5','6','0'],historicalRenderer:true,contentFingerprint:true,incrementalIndex:true,chatIngestion:true},reconcileTtlSeconds:RECONCILE_TTL/1000});
if(url.pathname==='/api/cards/ingest'&&request.method==='POST')return await ingest(request,env);
if(url.pathname==='/api/index/reconcile'&&request.method==='POST'){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);return json({ok:true,...await reconcileIndex(env,true)})}
if((url.pathname==='/api/dashboard'||url.pathname==='/api/cards/search')&&request.method==='GET'&&await authorized(request,env)){try{await reconcileIndex(env,false)}catch(e){console.error('Index reconcile:',e.message)}}
return await app.fetch(request,env)}catch(e){return json({error:e.message},500)}}};