const BASE='https://api.airtable.com/v0';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}})}
async function airtable(env,table,params='',init={}){
  if(!env.AIRTABLE_TOKEN) throw new Error('AIRTABLE_TOKEN secret is not configured');
  const r=await fetch(`${BASE}/${env.AIRTABLE_BASE_ID}/${encodeURIComponent(table)}${params}`,{...init,headers:{Authorization:`Bearer ${env.AIRTABLE_TOKEN}`,'content-type':'application/json',...(init.headers||{})}});
  if(!r.ok) throw new Error(`Airtable ${r.status}: ${await r.text()}`);
  return r.json();
}
async function getAll(env,table,limit=1000){let offset='',records=[];do{const q=new URLSearchParams({pageSize:'100'});if(offset)q.set('offset',offset);const d=await airtable(env,table,`?${q}`);records.push(...(d.records||[]));offset=d.offset||''}while(offset&&records.length<limit);return records}
function clean(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function normalizeCard(r){const f=r.fields||{};return{id:r.id,ankiId:f['ID Externo']||'',front:f['Frente / Texto']||'',body:f['Verso / Observações']||'',historicalContext:f['Contexto Histórico da Doutrina']||'',historicalStatus:(f['Contexto Histórico da Doutrina']?'Enriquecido':'Original importado'),contextInAnki:!!f['Contexto incorporado ao Anki'],historicalUpdatedAt:f['Atualizado no Contexto Histórico em']||null,concepts:(Array.isArray(f['Conceitos vinculados'])&&f['Conceitos vinculados'].length)?f['Conceitos vinculados']:(f['Conceitos detectados (IA)']||[]),themes:(Array.isArray(f['Temas vinculados'])&&f['Temas vinculados'].length)?f['Temas vinculados']:(f['Temas detectados (IA)']||[]),raw:f}}
function cardText(c){return clean(`${c.front} ${c.body} ${c.historicalContext||''}`)}
function mapBy(records,field){return new Map(records.map(r=>[r.id,clean(r.fields?.[field]||'')]))}
function names(ids,map){return(ids||[]).map(id=>map.get(String(id))).filter(Boolean)}
async function knowledge(env){const[cards,concepts,themes,rels,timeline]=await Promise.all([getAll(env,'Cartões',700),getAll(env,'Conceitos',500),getAll(env,'Temas',200),getAll(env,'Relações Doutrinárias',500),getAll(env,'Linha Histórica',200)]);return{cards:cards.map(normalizeCard),concepts:mapBy(concepts,'Conceito'),themes:mapBy(themes,'Tema'),rels:rels.map(r=>({o:clean(r.fields?.['Origem']||''),v:clean(r.fields?.['Verbo']?.name||r.fields?.['Verbo']||''),d:clean(r.fields?.['Destino']||''),why:r.fields?.['Justificativa']||''})),timeline:timeline.map(r=>({m:clean(r.fields?.['Marco']||''),t:clean(r.fields?.['Tema']||''),why:r.fields?.['Relação com anterior']||r.fields?.['Descrição']||'',order:Number(r.fields?.['Ordem']||0)})).sort((a,b)=>a.order-b.order)}}
function relationEvidence(a,b,k){const A=[...names(a.concepts,k.concepts),...names(a.themes,k.themes)],B=[...names(b.concepts,k.concepts),...names(b.themes,k.themes)];for(const r of k.rels){const direct=A.some(x=>r.o&& (r.o.includes(x)||x.includes(r.o)))&&B.some(x=>r.d&&(r.d.includes(x)||x.includes(r.d)));const reverse=A.some(x=>r.d&&(r.d.includes(x)||x.includes(r.d)))&&B.some(x=>r.o&&(r.o.includes(x)||x.includes(r.o)));if(!direct&&!reverse)continue;let kind='Aprofundamento';if(/crit|contr|diverg|opoe|exce/.test(r.v))kind='Contraste';else if(/evol|desenvol|ampl|supera|sucede/.test(r.v))kind=direct?'Evolução':'Origem';else if(/orig|fundament|anteced|pressup/.test(r.v))kind=reverse?'Origem':'Aprofundamento';return{score:24,kind,why:r.why}}return{score:0,kind:'',why:''}}
function historicalEvidence(a,b,k){const A=cardText(a),B=cardText(b),ma=k.timeline.find(x=>(x.m&&A.includes(x.m))||(x.t&&A.includes(x.t))),mb=k.timeline.find(x=>(x.m&&B.includes(x.m))||(x.t&&B.includes(x.t)));if(!ma||!mb)return{score:0,kind:'',why:''};const d=mb.order-ma.order;return{score:d?18:5,kind:d>0?'Evolução':d<0?'Origem':'Aprofundamento',why:mb.why||ma.why||''}}
function score(a,b,visited,k){if(!b||a.id===b.id||visited.has(b.id))return{score:-999};const A=cardText(a),B=cardText(b);let s=0;for(const w of [...new Set(A.match(/[a-z]{5,}/g)||[])].slice(0,90))if(B.includes(w))s++;for(const c of b.concepts||[])if((a.concepts||[]).includes(c))s+=9;for(const t of b.themes||[])if((a.themes||[]).includes(t))s+=5;const rel=relationEvidence(a,b,k),hist=historicalEvidence(a,b,k);s+=rel.score+hist.score;if(/jellinek/.test(A)&&/haberle|activus processualis/.test(B))s+=35;if(/activus processualis|haberle/.test(A)&&/amicus curiae|audiencia publica/.test(B))s+=30;return{score:s,rel,hist}}
function kindFor(a,b,e){if(e.rel.kind)return e.rel.kind;if(e.hist.kind)return e.hist.kind;const A=cardText(a),B=cardText(b);if(/jellinek/.test(A)&&/haberle|activus processualis/.test(B))return'Evolução';if(/critica|contrap|dworkin|hart|waldron|sandel|nozick/.test(B))return'Contraste';if(/origem|estado liberal|histor|seculo xix|antecedente/.test(B))return'Origem';return'Aprofundamento'}
function label(k){return k==='Origem'?'Quero entender de onde isso veio':k==='Evolução'?'Quero avançar historicamente':k==='Contraste'?'Quero ver outra forma de pensar o problema':'Quero aprofundar a teoria'}
function bridge(a,b,k,e){if(e.rel.why)return e.rel.why;if(e.hist.why)return e.hist.why;if(k==='Evolução'&&/jellinek/.test(cardText(a))&&/activus processualis|haberle/.test(cardText(b)))return'Jellinek descreve o status activus como a posição em que o indivíduo participa da formação da vontade estatal. Häberle amplia essa lógica para o status activus processualis, levando a participação também aos procedimentos decisórios do Poder Público.';return k==='Origem'?'Este caminho recua para o contexto intelectual que ajuda a explicar a construção estudada.':k==='Contraste'?'Este caminho mantém o problema jurídico, mas troca a lente teórica para permitir comparação.':k==='Evolução'?'Este caminho avança para uma formulação posterior que desenvolve a ideia sem romper sua continuidade intelectual.':'Este caminho aprofunda um desdobramento específico da formulação atual.'}
async function createFio(env,c){const p={records:[{fields:{'Fio':`Fio — ${c.ankiId||c.id}`,'Cartão inicial':[c.id],'Cartão atual':[c.id],'Percurso':c.ankiId||c.id,'Passos':0,'Status':'Em andamento','Observações':'Percurso iniciado pela interface Puxe o Fio.'}}]};const d=await airtable(env,'Fios de Estudo','',{method:'POST',body:JSON.stringify(p)});return d.records?.[0]?.id||null}
async function saveContext(env,body){const cards=(await getAll(env,'Cartões',700)).map(normalizeCard);const c=cards.find(x=>x.id===body.cardId||x.ankiId===body.cardId);if(!c)throw new Error('Card not found');const fields={'Contexto Histórico da Doutrina':body.context||'','Status de enriquecimento histórico':body.context?'Enriquecido':'Original importado','Contexto incorporado ao Anki':!!body.contextInAnki,'Atualizado no Contexto Histórico em':new Date().toISOString()};await airtable(env,'Cartões','',{method:'PATCH',body:JSON.stringify({records:[{id:c.id,fields}]})});return c.id}
async function api(request,env,url){
  if(url.pathname==='/api/health')return json({ok:true,base:env.AIRTABLE_BASE_ID});
  if(url.pathname==='/api/thread'&&request.method==='GET'){const id=url.searchParams.get('id'),visited=new Set((url.searchParams.get('visited')||'').split(',').filter(Boolean)),k=await knowledge(env),current=k.cards.find(c=>c.id===id||c.ankiId===id)||k.cards[0];if(!current)return json({error:'No cards available'},404);visited.add(current.id);const ranked=k.cards.map(card=>({card,e:score(current,card,visited,k)})).filter(x=>x.e.score>0).sort((a,b)=>b.e.score-a.e.score).slice(0,24),opts=[],seen=new Set();for(const x of ranked){const kind=kindFor(current,x.card,x.e);if(seen.has(kind)&&opts.length<3)continue;seen.add(kind);opts.push({kind,label:label(kind),card:x.card,score:x.e.score,bridge:bridge(current,x.card,kind,x.e),basis:x.e.rel.score?'grafo doutrinário':x.e.hist.score?'linha histórica':'afinidade do acervo'});if(opts.length>=4)break}return json({current,options:opts})}
  if(url.pathname==='/api/card/context'&&request.method==='PATCH'){const id=await saveContext(env,await request.json());return json({ok:true,cardId:id})}
  if(url.pathname==='/api/fio/start'&&request.method==='POST'){const body=await request.json(),cards=(await getAll(env,'Cartões',700)).map(normalizeCard),c=cards.find(x=>x.id===body.cardId||x.ankiId===body.cardId);if(!c)return json({error:'Card not found'},404);return json({fioId:await createFio(env,c)})}
  if(url.pathname.startsWith('/api/fio/')&&request.method==='PATCH'){const fioId=url.pathname.split('/').pop(),b=await request.json();if(!/^rec[A-Za-z0-9]{14}$/.test(fioId))return json({error:'Invalid fio id'},400);await airtable(env,'Fios de Estudo','',{method:'PATCH',body:JSON.stringify({records:[{id:fioId,fields:{'Cartão atual':[b.currentCardId],'Percurso':b.path||'','Último caminho escolhido':b.kind||'Aprofundamento','Última transição contextual':b.bridge||'','Passos':Number(b.steps||0),'Status':b.status||'Em andamento'}}]})});return json({ok:true})}
  return null
}
export default{async fetch(request,env){const url=new URL(request.url);try{if(url.pathname.startsWith('/api/')){const r=await api(request,env,url);return r||json({error:'API route not found'},404)}return env.ASSETS.fetch(request)}catch(e){return json({error:e.message},500)}}};
