import app from './worker.js';

const BASE='https://api.airtable.com/v0';
let lastReconcile=0;
const RECONCILE_TTL=10*60*1000;

function clean(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function authorized(request,env){const key=request.headers.get('x-puxe-key')||'';return !!key&&(await sha256(key))===env.APP_ACCESS_HASH}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function airtable(env,table,params='',init={}){let last='';for(let attempt=0;attempt<5;attempt++){const r=await fetch(`${BASE}/${env.AIRTABLE_BASE_ID}/${encodeURIComponent(table)}${params}`,{...init,headers:{Authorization:`Bearer ${env.AIRTABLE_TOKEN}`,'content-type':'application/json',...(init.headers||{})}});if(r.ok)return r.json();last=await r.text();if(r.status!==429&&r.status<500)throw new Error(`Airtable ${r.status}: ${last}`);await sleep(220*Math.pow(2,attempt)+Math.floor(Math.random()*120))}throw new Error(`Airtable temporariamente indisponível: ${last}`)}
async function getAll(env,table,limit=1500,extra={}){let offset='',records=[];do{const q=new URLSearchParams({pageSize:'100',...extra});if(offset)q.set('offset',offset);const d=await airtable(env,table,`?${q}`);records.push(...(d.records||[]));offset=d.offset||''}while(offset&&records.length<limit);return records}
function words(s){return new Set((clean(s).match(/[a-z0-9]{4,}/g)||[]))}
function similarity(a,b){const A=words(a),B=words(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(A.size,B.size)}
function indexFields(card){const f=card.fields||{},id=f['ID Externo']||card.id,front=String(f['Frente / Texto']||''),back=String(f['Verso / Observações']||''),ctx=String(f['Contexto Histórico da Doutrina']||''),theme=String(f['Tema sugerido']||''),concepts=String(f['Conceitos sugeridos']||'');return{'Entrada':`${id} — ${(front||back||'Cartão').replace(/\s+/g,' ').slice(0,110)}`,'Tipo':'Cartão','Resumo pesquisável':`${front}\n${back}\n${ctx}`.slice(0,8000),'Palavras-chave':`${theme}; ${concepts}`.slice(0,3000),'Tabela fonte':'Cartões','Registro fonte':card.id,'Provenance':`${f['Origem da ingestão']?.name||f['Origem da ingestão']||'Airtable'}${f['Fingerprint do conteúdo']?` · fingerprint ${f['Fingerprint do conteúdo']}`:''}`,'Status':'Ativo'}}
async function ensureIndexForCard(env,card,indexRows){let idx=indexRows.find(r=>String(r.fields?.['Registro fonte']||'')===card.id);const fields=indexFields(card);if(idx){await airtable(env,'Índice Universal','',{method:'PATCH',body:JSON.stringify({records:[{id:idx.id,fields}]})});return'updated'}await airtable(env,'Índice Universal','',{method:'POST',body:JSON.stringify({records:[{fields}]})});return'created'}
async function reconcileIndex(env,force=false){if(!force&&Date.now()-lastReconcile<RECONCILE_TTL)return{skipped:true};const cards=await getAll(env,'Cartões',1200);await sleep(250);const index=await getAll(env,'Índice Universal',1800);const indexed=new Set(index.map(r=>String(r.fields?.['Registro fonte']||'')));let created=0;for(const card of cards){if(indexed.has(card.id))continue;await ensureIndexForCard(env,card,index);indexed.add(card.id);created++;await sleep(120)}lastReconcile=Date.now();return{cards:cards.length,index:index.length+created,created}}
function publicSearchCard(r){const f=r.fields||{};return{id:r.id,ankiId:f['ID Externo']||'',front:f['Frente / Texto']||'',body:f['Verso / Observações']||'',historicalContext:f['Contexto Histórico da Doutrina']||'',historicalStatus:f['Contexto Histórico da Doutrina']?'Enriquecido':'Original importado',annotations:[],concepts:[],themes:f['Tema sugerido']?[String(f['Tema sugerido'])]:[],authors:[],theories:[]}}
function formulaString(v){return String(v).replace(/\\/g,'\\\\').replace(/"/g,'\\"')}
async function directSearch(request,env,url){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);const q=String(url.searchParams.get('q')||'').trim();if(!q){const params=new URLSearchParams({pageSize:'24',maxRecords:'24'});const d=await airtable(env,'Cartões',`?${params}`);return json({results:(d.records||[]).map(publicSearchCard),mode:'direct'})}const exact=/^(ANKI-\d{4}|CHAT-[A-Za-z0-9-]+|CARD-[A-Za-z0-9-]+)$/i.test(q);const escaped=formulaString(q);const formula=exact?`{ID Externo}="${escaped}"`:`OR(SEARCH(LOWER("${escaped}"),LOWER({ID Externo}&" "&{Frente / Texto}&" "&{Verso / Observações})),SEARCH(LOWER("${escaped}"),LOWER({Contexto Histórico da Doutrina})))`;const params=new URLSearchParams({pageSize:'24',maxRecords:'24',filterByFormula:formula});const d=await airtable(env,'Cartões',`?${params}`);return json({results:(d.records||[]).map(publicSearchCard),mode:'direct'})}
function safeMap(f,current){try{const m=JSON.parse(String(f['Mapa do fio']||''));if(m&&m.nodes)return m}catch{}if(!current)return{root:null,nodes:{}};return{root:current.id,nodes:{[current.id]:{cardId:current.id,ankiId:current.ankiId,title:(current.front||current.body||current.ankiId).slice(0,120),children:[]}}}}
async function cardsByIds(env,ids){const list=[...new Set(ids.filter(Boolean))];if(!list.length)return new Map();const formula=`OR(${list.map(id=>`RECORD_ID()="${formulaString(id)}"`).join(',')})`;const params=new URLSearchParams({pageSize:'100',maxRecords:String(list.length),filterByFormula:formula});const d=await airtable(env,'Cartões',`?${params}`);return new Map((d.records||[]).map(r=>[r.id,publicSearchCard(r)]))}
async function listFiosLite(env){const rows=await getAll(env,'Fios de Estudo',500);rows.sort((a,b)=>String(b.fields?.['Último acesso']||b.createdTime||'').localeCompare(String(a.fields?.['Último acesso']||a.createdTime||'')));const currentIds=rows.map(r=>(r.fields?.['Cartão atual']||[])[0]).filter(Boolean);const cmap=await cardsByIds(env,currentIds);return rows.map(r=>{const f=r.fields||{},currentId=(f['Cartão atual']||[])[0],current=cmap.get(currentId)||null,map=safeMap(f,current);return{id:r.id,name:f['Fio']||'Fio',status:f['Status']||'Em andamento',path:f['Percurso']||'',steps:Number(f['Passos']||0),lastAccess:f['Último acesso']||r.createdTime,current,map,summary:f['Resumo da descoberta']||'',createdTime:r.createdTime}})}
async function lightweightDashboard(request,env){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);const fios=await listFiosLite(env);const enriched=await getAll(env,'Cartões',1000,{filterByFormula:'NOT({Contexto Histórico da Doutrina}="")'});const positives=await getAll(env,'Histórico',1000,{filterByFormula:'{Depois}="positivo"'});return json({stats:{fios:fios.length,enriched:enriched.length,transitions:fios.reduce((n,x)=>n+x.steps,0),validated:positives.length},recent:fios.slice(0,5),mode:'lightweight'})}
async function ingest(request,env){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);const b=await request.json();const front=String(b.front||'').trim(),back=String(b.back||'').trim(),deck=String(b.deck||'Novo baralho').trim();if(!front&&!back)return json({error:'Informe frente ou verso do cartão.'},400);const fp=(await sha256(`${clean(deck)}|${clean(front)}|${clean(back)}`)).slice(0,16);const cards=await getAll(env,'Cartões',1200);const exact=cards.find(r=>String(r.fields?.['Fingerprint do conteúdo']||'')===fp||(b.externalId&&String(r.fields?.['ID Externo']||'')===String(b.externalId)));if(exact)return json({ok:true,status:'existing',cardId:exact.id,externalId:exact.fields?.['ID Externo'],fingerprint:fp});const near=cards.map(r=>({r,s:similarity(front,String(r.fields?.['Frente / Texto']||''))})).filter(x=>x.s>=0.92).sort((a,b)=>b.s-a.s).slice(0,3);if(near.length)return json({error:'Possível cartão já existente. Criação bloqueada para revisão conservadora.',fingerprint:fp,candidates:near.map(x=>({id:x.r.id,externalId:x.r.fields?.['ID Externo'],similarity:Number(x.s.toFixed(3)),front:String(x.r.fields?.['Frente / Texto']||'').slice(0,220)}))},409);const externalId=String(b.externalId||`CARD-${fp.slice(0,12).toUpperCase()}`),now=new Date().toISOString();const fields={'ID Externo':externalId,'Frente / Texto':front,'Verso / Observações':back,'Baralho Anki':deck,'Origem da ingestão':'Chat — estudo','Inserido na base em':now,'Fingerprint do conteúdo':fp};if(b.origin)fields['Origem / Banca']=String(b.origin);if(b.tags)fields['Tags originais']=String(b.tags);if(b.theme)fields['Tema sugerido']=String(b.theme);if(b.concepts)fields['Conceitos sugeridos']=Array.isArray(b.concepts)?b.concepts.join('; '):String(b.concepts);if(b.historicalContext){fields['Contexto Histórico da Doutrina']=String(b.historicalContext);fields['Status de enriquecimento histórico']='Enriquecido';fields['Origem do enriquecimento histórico']='Contexto Histórico da Doutrina';fields['Versão do contexto histórico']=1;fields['Atualizado no Contexto Histórico em']=now}const created=await airtable(env,'Cartões','',{method:'POST',body:JSON.stringify({records:[{fields}]})});const card=created.records?.[0];if(!card)throw new Error('Cartão não foi criado.');const indexRows=await getAll(env,'Índice Universal',1800);await ensureIndexForCard(env,card,indexRows);await airtable(env,'Histórico','',{method:'POST',body:JSON.stringify({records:[{fields:{'Evento':'Ingestão de cartão por chat','Alvo externo':externalId,'Depois':`Criado ${externalId} · fingerprint ${fp}`,'Observações':'Ingestão + deduplicação determinística + indexação incremental. Conteúdo original preservado.'}}]})});lastReconcile=0;return json({ok:true,status:'created',cardId:card.id,externalId,fingerprint:fp,indexed:true},201)}

export default{async fetch(request,env){const url=new URL(request.url);try{if(url.pathname==='/api/health'&&request.method==='GET')return json({ok:true,version:'2.2.2',features:{readerTools:true,keyboardShortcuts:['1','2','3','4','5','6','0'],historicalRenderer:true,contentFingerprint:true,incrementalIndex:true,chatIngestion:true,directCardSearch:true,lightweightDashboard:true,lightweightThreadList:true,readTimeReconcile:false,airtableBackoff:true}});if(url.pathname==='/api/dashboard'&&request.method==='GET')return await lightweightDashboard(request,env);if(url.pathname==='/api/fios'&&request.method==='GET'){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);return json({fios:await listFiosLite(env),mode:'lightweight'})}if(url.pathname==='/api/cards/search'&&request.method==='GET')return await directSearch(request,env,url);if(url.pathname==='/api/cards/ingest'&&request.method==='POST')return await ingest(request,env);if(url.pathname==='/api/index/reconcile'&&request.method==='POST'){if(!(await authorized(request,env)))return json({error:'Acesso não autorizado'},401);return json({ok:true,...await reconcileIndex(env,true)})}return await app.fetch(request,env)}catch(e){console.error('Puxe v2.2.2',e);return json({error:e.message||'Falha na operação'},500)}}};